controller_list:
  - name: fake_leg_1_controller
    type: $(arg fake_execution_type)
    joints:
      - coxa1
      - femur1
      - tibia1
  - name: fake_leg_2_controller
    type: $(arg fake_execution_type)
    joints:
      - coxa2
      - femur2
      - tibia2
  - name: fake_leg_3_controller
    type: $(arg fake_execution_type)
    joints:
      - coxa3
      - femur3
      - tibia3
  - name: fake_leg_4_controller
    type: $(arg fake_execution_type)
    joints:
      - coxa4
      - femur4
      - tibia4
  - name: fake_eef_1_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef_2_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef_3_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef_4_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: leg_1
    pose: default
  - group: leg_2
    pose: default
  - group: leg_3
    pose: default
  - group: leg_4
    pose: deafult